import styles from "./Infopage.module.css"
import planet from "/planet.png"
import saveTheEarth from "/save-the-earth.png"
import submarine from "/submarine.png"
import turtle from "/turtle.png"
import waterTemp from "/water-temperature.png"
import ScrollToTop from "../components/scrollToTop"
import ContinueBtn from "../components/ContinueBtn"
import BackBtn from "../components/backBtn"

import { useEffect, useState } from "react"
import { useLocation } from "react-router-dom"

export default function Infopage() {

    const [scrollPosition, setScrollPosition] = useState(0);
    const [percentScrolled, setPercentScrolled] = useState(0)


    const location = useLocation().pathname;

    useEffect(() => {
        const handlescroll = () => {
            const position = window.scrollY;
            setScrollPosition(position)
            // const fullHeight = window.innerHeight * 3;
            setPercentScrolled((position / 1835) * 100); /**The 1870 represents the MAX Height */
        }
        window.addEventListener("scroll", handlescroll)

        return () => {
            window.removeEventListener("scroll", handlescroll)
        }

    }, [])


    return (
        <>
            <ScrollToTop />
            <div className={styles.background}>
                <div className={`${styles.progressbarBackground} bg-slate-700 fixed z-10`}
                    style={{ top: scrollPosition < 40 ? 50 - scrollPosition : 10 }} >

                    <div className={`${styles.progressbar} bg-teal-500`}
                        style={{ width: `${percentScrolled}%` }}></div>
                </div>


                <img className={`${styles.image} ${styles.img1}`} src={planet}
                    style={{
                        height: "301px",
                        width: "300px"
                    }} />

                <img className={`${styles.image} ${styles.img2}`} src={saveTheEarth}
                    style={{
                        height: " ",
                        width: "50vw"
                    }} />
                <img className={`${styles.image} ${styles.img3}`} src={submarine}
                    style={{
                        height: "20vh",
                        width: "40vw"
                    }} />

                <img className={`${styles.image} ${styles.img4}`} src={turtle}
                    style={{
                        height: "20vh",
                        width: "40vw"
                    }} />
                <img className={`${styles.image} ${styles.img5}`} src={waterTemp}
                    style={{
                        height: "20vh",
                        width: "40vw"
                    }} />



                <div className={styles.section} >
                    <div className={styles.container}>
                        <div className={styles.headingText}>information</div>
                        <h3 className={styles.infoText}>
                            The ocean, as the planet’s greatest carbon sink, absorbs excess heat and energy from rising greenhouse gas emissions.
                            Currently, the ocean has absorbed about 90 percent of the heat generated by these emissions.
                            Warming of the ocean from this heat causes cascading effects, including ice melting, sea-level rise, marine heatwaves, and ocean acidification.



                        </h3>    </div>
                    <br />

                </div>

                <div className={styles.section} >
                    <div className={styles.container}>
                        <div className={styles.headingText}>information</div>
                        <h3 className={styles.infoText}>

                            These impacts have lasting effects on marine biodiversity and the lives of coastal communities.
                            Around 680 million people live in low-lying coastal areas affected by these changes.
                            Nearly 2 billion people live in coastal megacities facing related challenges.
                            Approximately half of the global population (3.3 billion) relies on fish as a primary source of protein.
                            Nearly 60 million people are employed in fisheries and the aquaculture sector worldwide.



                        </h3>
                    </div>
                    <br />

                </div>

                <div className={styles.section} >
                    <div className={styles.container}>
                        <div className={styles.headingText}>information</div>
                        <h3 className={styles.infoText}>Sea-level rise has accelerated in recent decades due to increasing ice loss in the polar regions.
                            According to the World Meteorological Organization, global mean sea level reached a record high in 2021, rising an average of 4.5 millimeters per year from 2013 to 2021.

                        </h3>
                    </div>
                    <br />

                </div>
                <div className="flex justify-space-around ">
                    <BackBtn page={location} />
                    <div className="w-0.5"></div>
                    <ContinueBtn page={location} />
                </div>

            </div>
        </>
    )
}